DROP TABLE IF EXISTS FLICKR;

CREATE TABLE FLICKR (
  id VARCHAR2(12 CHAR) NOT NULL,
  tag VARCHAR2(15 CHAR) NOT NULL,
  secret VARCHAR2(10 CHAR) NOT NULL,
  server VARCHAR2(8 CHAR) NOT NULL,
  title VARCHAR2(50 CHAR) NOT NULL,
  PRIMARY KEY(id,tag)
);